### ISSUE TITLE
Why would anyone create such package as this one?

### ISSUE THREAD

**Issue by hamsterready** [sindresorhus/has-flag#11]
Would love to find out why this package was even created? And it would be great to understand motivation of developers who use this package.

BTW, `startsWith` is not supported in IE11. 

BTW2, package does not support any kind of escaping.

**Comment by sindresorhus** [comment]
I think you opened this on the wrong repo as this is neither meant for the browser nor need of any escaping.

**Comment by hamsterready** [comment]
You are right by saying that you are not responsible for stupid-as-f*ck developers who use this package. But why did you spend energy on creating package to wrap `indexOf()`? This is still valid question ;)

**Comment by Qix-** [comment]
@hamsterready I don't think Github is the right place for you, buddy.

**Comment by dino-zhao** [comment]
+1
